services:
  db:
    image: postgres:16
    container_name: postgres16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: iptv-mapper
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: iptv-mapper
      TZ: Europe/London
    volumes:
      - pgdata:/var/lib/postgresql/data
      # initialization scripts (run only on first startup)
      - ./scripts/sql/initial:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iptv-mapper || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    environment:
      APP_INGEST_ENABLED: "true"
      APP_INGEST_CRON: "0 0 3 * * *"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/iptv-mapper"
      DB_URL: jdbc:postgresql://home-postgresql-sr01:5432/iptv-mapper
      DB_USER: iptv-mapper
      DB_PASSWORD: change-me
      SPRING_FLYWAY_LOCATIONS: filesystem:/app/db/init
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      JPA_DDL_AUTO: "validate"
      HIBERNATE_SHOW_SQL: "true"
      HIBERNATE_FORMAT_SQL: "false"
      JDBC_TIME_ZONE: "UTC"
      APP_CLEANUP_DAYS: "7"
      SPRING_APPLICATION_NAME: "iptv-mapper"
      SERVER_PORT: "8080"
      IPTV_BASE_URL: "http://localhost:8080"
      # OpenTelemetry settings
      OTEL_SERVICE_NAME: iptv-mapper
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=prod
      OTEL_EXPORTER_OTLP_ENDPOINT: http://loki:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      # Optional: override to pin agent version
      # OTEL_JAVA_AGENT_URL: https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.8.0/opentelemetry-javaagent.jar
    # For local environment.
    image: iptv-mapper:latest
    # For remote deployment.
#    image: ghcr.io/smling/iptv-mapper:latest
    container_name: iptv-mapper
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db
    volumes:
      - otelcache:/otel
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        mode: non-blocking
        max-buffer-size: 4m
        loki-external-labels: "job=iptv-mapper,container={{.Name}},compose_service={{.Service}}"

volumes:
  pgdata:
  otelcache:

