INSERT INTO data_source (type, url, label, country_code, priority)
VALUES
  ('EPG','https://www.open-epg.com/files/albania1.xml','Open-EPG Albania 1','AL',50),
  ('EPG','https://www.open-epg.com/files/argentina1.xml','Open-EPG Argentina 1','AR',50),
  ('EPG','https://www.open-epg.com/files/argentina2.xml','Open-EPG Argentina 2','AR',50),
  ('EPG','https://www.open-epg.com/files/argentina3.xml','Open-EPG Argentina 3','AR',50),
  ('EPG','https://www.open-epg.com/files/argentina4.xml','Open-EPG Argentina 4','AR',50),
  ('EPG','https://www.open-epg.com/files/argentina5.xml','Open-EPG Argentina 5','AR',50),
  ('EPG','https://www.open-epg.com/files/australia1.xml','Open-EPG Australia 1','AU',50),
  ('EPG','https://www.open-epg.com/files/australia2.xml','Open-EPG Australia 2','AU',50),
  ('EPG','https://www.open-epg.com/files/australia3.xml','Open-EPG Australia 3','AU',50),
  ('EPG','https://www.open-epg.com/files/australia4.xml','Open-EPG Australia 4','AU',50),
  ('EPG','https://www.open-epg.com/files/austria1.xml','Open-EPG Austria 1','AT',50),
  ('EPG','https://www.open-epg.com/files/austria2.xml','Open-EPG Austria 2','AT',50),
  ('EPG','https://www.open-epg.com/files/austria3.xml','Open-EPG Austria 3','AT',50),
  ('EPG','https://www.open-epg.com/files/austria4.xml','Open-EPG Austria 4','AT',50),
  ('EPG','https://www.open-epg.com/files/belgium.xml','Open-EPG Belgium','BE',50),
  ('EPG','https://www.open-epg.com/files/bolivia1.xml','Open-EPG Bolivia 1','BO',50),
  ('EPG','https://www.open-epg.com/files/bolivia2.xml','Open-EPG Bolivia 2','BO',50),
  ('EPG','https://www.open-epg.com/files/bosnia1.xml','Open-EPG Bosnia 1','BA',50),
  ('EPG','https://www.open-epg.com/files/brazil1.xml','Open-EPG Brazil 1','BR',50),
  ('EPG','https://www.open-epg.com/files/brazil2.xml','Open-EPG Brazil 2','BR',50),
  ('EPG','https://www.open-epg.com/files/brazil3.xml','Open-EPG Brazil 3','BR',50),
  ('EPG','https://www.open-epg.com/files/brazil4.xml','Open-EPG Brazil 4','BR',50),
  ('EPG','https://www.open-epg.com/files/bulgaria1.xml','Open-EPG Bulgaria 1','BG',50),
  ('EPG','https://www.open-epg.com/files/bulgaria2.xml','Open-EPG Bulgaria 2','BG',50),
  ('EPG','https://www.open-epg.com/files/bulgaria4.xml','Open-EPG Bulgaria 4','BG',50),
  ('EPG','https://www.open-epg.com/files/canada1.xml','Open-EPG Canada 1','CA',50),
  ('EPG','https://www.open-epg.com/files/canada2.xml','Open-EPG Canada 2','CA',50),
  ('EPG','https://www.open-epg.com/files/canada3.xml','Open-EPG Canada 3','CA',50),
  ('EPG','https://www.open-epg.com/files/canada4.xml','Open-EPG Canada 4','CA',50),
  ('EPG','https://www.open-epg.com/files/canada5.xml','Open-EPG Canada 5','CA',50),
  ('EPG','https://www.open-epg.com/files/canada6.xml','Open-EPG Canada 6','CA',50),
  ('EPG','https://www.open-epg.com/files/canada7.xml','Open-EPG Canada 7','CA',50),
  ('EPG','https://www.open-epg.com/files/chile1.xml','Open-EPG Chile 1','CL',50),
  ('EPG','https://www.open-epg.com/files/chile2.xml','Open-EPG Chile 2','CL',50),
  ('EPG','https://www.open-epg.com/files/china1.xml','Open-EPG China 1','CN',50),
  ('EPG','https://www.open-epg.com/files/china3.xml','Open-EPG China 3','CN',50),
  ('EPG','https://www.open-epg.com/files/colombia1.xml','Open-EPG Colombia 1','CO',50),
  ('EPG','https://www.open-epg.com/files/colombia2.xml','Open-EPG Colombia 2','CO',50),
  ('EPG','https://www.open-epg.com/files/costarica1.xml','Open-EPG Costa Rica 1','CR',50),
  ('EPG','https://www.open-epg.com/files/croatia1.xml','Open-EPG Croatia 1','HR',50),
  ('EPG','https://www.open-epg.com/files/croatia2.xml','Open-EPG Croatia 2','HR',50),
  ('EPG','https://www.open-epg.com/files/croatia3.xml','Open-EPG Croatia 3','HR',50),
  ('EPG','https://www.open-epg.com/files/croatia4.xml','Open-EPG Croatia 4','HR',50),
  ('EPG','https://www.open-epg.com/files/croatia5.xml','Open-EPG Croatia 5','HR',50),
  ('EPG','https://www.open-epg.com/files/croatia6.xml','Open-EPG Croatia 6','HR',50),
  ('EPG','https://www.open-epg.com/files/croatia7.xml','Open-EPG Croatia 7','HR',50),
  ('EPG','https://www.open-epg.com/files/cyprus1.xml','Open-EPG Cyprus 1','CY',50),
  ('EPG','https://www.open-epg.com/files/czech3.xml','Open-EPG Czech 3','CZ',50),
  ('EPG','https://www.open-epg.com/files/czech4.xml','Open-EPG Czech 4','CZ',50),
  ('EPG','https://www.open-epg.com/files/denmark1.xml','Open-EPG Denmark 1','DK',50),
  ('EPG','https://www.open-epg.com/files/denmark2.xml','Open-EPG Denmark 2','DK',50),
  ('EPG','https://www.open-epg.com/files/denmark3.xml','Open-EPG Denmark 3','DK',50),
  ('EPG','https://www.open-epg.com/files/denmark4.xml','Open-EPG Denmark 4','DK',50),
  ('EPG','https://www.open-epg.com/files/denmark5.xml','Open-EPG Denmark 5','DK',50),
  ('EPG','https://www.open-epg.com/files/denmark6.xml','Open-EPG Denmark 6','DK',50),
  ('EPG','https://www.open-epg.com/files/dominican1.xml','Open-EPG Dominican Republic 1','DO',50),
  ('EPG','https://www.open-epg.com/files/ecuador1.xml','Open-EPG Ecuador 1','EC',50),
  ('EPG','https://www.open-epg.com/files/egypt1.xml','Open-EPG Egypt 1','EG',50),
  ('EPG','https://www.open-epg.com/files/egypt2.xml','Open-EPG Egypt 2','EG',50),
  ('EPG','https://www.open-epg.com/files/elsalvador1.xml','Open-EPG El Salvador 1','SV',50),
  ('EPG','https://www.open-epg.com/files/estonia1.xml','Open-EPG Estonia 1','EE',50),
  ('EPG','https://www.open-epg.com/files/finland1.xml','Open-EPG Finland 1','FI',50),
  ('EPG','https://www.open-epg.com/files/finland2.xml','Open-EPG Finland 2','FI',50),
  ('EPG','https://www.open-epg.com/files/finland3.xml','Open-EPG Finland 3','FI',50),
  ('EPG','https://www.open-epg.com/files/georgia1.xml','Open-EPG Georgia 1','GE',50),
  ('EPG','https://www.open-epg.com/files/georgia2.xml','Open-EPG Georgia 2','GE',50),
  ('EPG','https://www.open-epg.com/files/germany1.xml','Open-EPG Germany 1','DE',50),
  ('EPG','https://www.open-epg.com/files/germany2.xml','Open-EPG Germany 2','DE',50),
  ('EPG','https://www.open-epg.com/files/germany3.xml','Open-EPG Germany 3','DE',50),
  ('EPG','https://www.open-epg.com/files/germany4.xml','Open-EPG Germany 4','DE',50),
  ('EPG','https://www.open-epg.com/files/germany5.xml','Open-EPG Germany 5','DE',50),
  ('EPG','https://www.open-epg.com/files/ghana1.xml','Open-EPG Ghana 1','GH',50),
  ('EPG','https://www.open-epg.com/files/greece1.xml','Open-EPG Greece 1','GR',50),
  ('EPG','https://www.open-epg.com/files/greece2.xml','Open-EPG Greece 2','GR',50),
  ('EPG','https://www.open-epg.com/files/greece3.xml','Open-EPG Greece 3','GR',50),
  ('EPG','https://www.open-epg.com/files/guatemala1.xml','Open-EPG Guatemala 1','GT',50),
  ('EPG','https://www.open-epg.com/files/honduras1.xml','Open-EPG Honduras 1','HN',50),
  ('EPG','https://www.open-epg.com/files/hongkong1.xml','Open-EPG Hong Kong 1','HK',50),
  ('EPG','https://www.open-epg.com/files/hongkong2.xml','Open-EPG Hong Kong 2','HK',50),
  ('EPG','https://www.open-epg.com/files/hongkong3.xml','Open-EPG Hong Kong 3','HK',50),
  ('EPG','https://www.open-epg.com/files/hongkong4.xml','Open-EPG Hong Kong 4','HK',50),
  ('EPG','https://www.open-epg.com/files/hongkong5.xml','Open-EPG Hong Kong 5','HK',50),
  ('EPG','https://www.open-epg.com/files/hungary1.xml','Open-EPG Hungary 1','HU',50),
  ('EPG','https://www.open-epg.com/files/iceland1.xml','Open-EPG Iceland 1','IS',50),
  ('EPG','https://www.open-epg.com/files/iceland2.xml','Open-EPG Iceland 2','IS',50),
  ('EPG','https://www.open-epg.com/files/iceland3.xml','Open-EPG Iceland 3','IS',50),
  ('EPG','https://www.open-epg.com/files/india1.xml','Open-EPG India 1','IN',50),
  ('EPG','https://www.open-epg.com/files/india2.xml','Open-EPG India 2','IN',50),
  ('EPG','https://www.open-epg.com/files/india3.xml','Open-EPG India 3','IN',50),
  ('EPG','https://www.open-epg.com/files/india4.xml','Open-EPG India 4','IN',50),
  ('EPG','https://www.open-epg.com/files/india5.xml','Open-EPG India 5','IN',50),
  ('EPG','https://www.open-epg.com/files/indonesia1.xml','Open-EPG Indonesia 1','ID',50),
  ('EPG','https://www.open-epg.com/files/indonesia2.xml','Open-EPG Indonesia 2','ID',50),
  ('EPG','https://www.open-epg.com/files/indonesia3.xml','Open-EPG Indonesia 3','ID',50),
  ('EPG','https://www.open-epg.com/files/indonesia4.xml','Open-EPG Indonesia 4','ID',50),
  ('EPG','https://www.open-epg.com/files/indonesia5.xml','Open-EPG Indonesia 5','ID',50),
  ('EPG','https://www.open-epg.com/files/indonesia6.xml','Open-EPG Indonesia 6','ID',50),
  ('EPG','https://www.open-epg.com/files/ireland2.xml','Open-EPG Ireland 2','IE',50),
  ('EPG','https://www.open-epg.com/files/israel1.xml','Open-EPG Israel 1','IL',50),
  ('EPG','https://www.open-epg.com/files/israel2.xml','Open-EPG Israel 2','IL',50),
  ('EPG','https://www.open-epg.com/files/italy1.xml','Open-EPG Italy 1','IT',50),
  ('EPG','https://www.open-epg.com/files/italy2.xml','Open-EPG Italy 2','IT',50),
  ('EPG','https://www.open-epg.com/files/italy3.xml','Open-EPG Italy 3','IT',50),
  ('EPG','https://www.open-epg.com/files/italy4.xml','Open-EPG Italy 4','IT',50),
  ('EPG','https://www.open-epg.com/files/italy5.xml','Open-EPG Italy 5','IT',50),
  ('EPG','https://www.open-epg.com/files/italy6.xml','Open-EPG Italy 6','IT',50),
  ('EPG','https://www.open-epg.com/files/italy7.xml','Open-EPG Italy 7','IT',50),
  ('EPG','https://www.open-epg.com/files/italy8.xml','Open-EPG Italy 8','IT',50),
  ('EPG','https://www.open-epg.com/files/ivorycoast1.xml','Open-EPG Ivory Coast 1','CI',50),
  ('EPG','https://www.open-epg.com/files/jamaica1.xml','Open-EPG Jamaica 1','JM',50),
  ('EPG','https://www.open-epg.com/files/japan1.xml','Open-EPG Japan 1','JP',50),
  ('EPG','https://www.open-epg.com/files/japan2.xml','Open-EPG Japan 2','JP',50),
  ('EPG','https://www.open-epg.com/files/japan3.xml','Open-EPG Japan 3','JP',50),
  ('EPG','https://www.open-epg.com/files/kenya1.xml','Open-EPG Kenya 1','KE',50),
  ('EPG','https://www.open-epg.com/files/korea1.xml','Open-EPG Korea 1','KR',50),
  ('EPG','https://www.open-epg.com/files/latvia1.xml','Open-EPG Latvia 1','LV',50),
  ('EPG','https://www.open-epg.com/files/latvia2.xml','Open-EPG Latvia 2','LV',50),
  ('EPG','https://www.open-epg.com/files/lithuania1.xml','Open-EPG Lithuania 1','LT',50),
  ('EPG','https://www.open-epg.com/files/lithuania2.xml','Open-EPG Lithuania 2','LT',50),
  ('EPG','https://www.open-epg.com/files/lithuania3.xml','Open-EPG Lithuania 3','LT',50),
  ('EPG','https://www.open-epg.com/files/luxembourg1.xml','Open-EPG Luxembourg 1','LU',50),
  ('EPG','https://www.open-epg.com/files/macau1.xml','Open-EPG Macau 1','MO',50),
  ('EPG','https://www.open-epg.com/files/macedonia1.xml','Open-EPG North Macedonia 1','MK',50),
  ('EPG','https://www.open-epg.com/files/madagascar1.xml','Open-EPG Madagascar 1','MG',50),
  ('EPG','https://www.open-epg.com/files/malawi1.xml','Open-EPG Malawi 1','MW',50),
  ('EPG','https://www.open-epg.com/files/malaysia1.xml','Open-EPG Malaysia 1','MY',50),
  ('EPG','https://www.open-epg.com/files/malaysia2.xml','Open-EPG Malaysia 2','MY',50),
  ('EPG','https://www.open-epg.com/files/malaysia3.xml','Open-EPG Malaysia 3','MY',50),
  ('EPG','https://www.open-epg.com/files/malta1.xml','Open-EPG Malta 1','MT',50),
  ('EPG','https://www.open-epg.com/files/mauritius1.xml','Open-EPG Mauritius 1','MU',50),
  ('EPG','https://www.open-epg.com/files/mexico1.xml','Open-EPG Mexico 1','MX',50),
  ('EPG','https://www.open-epg.com/files/mexico2.xml','Open-EPG Mexico 2','MX',50),
  ('EPG','https://www.open-epg.com/files/mongolia1.xml','Open-EPG Mongolia 1','MN',50),
  ('EPG','https://www.open-epg.com/files/montenegro1.xml','Open-EPG Montenegro 1','ME',50),
  ('EPG','https://www.open-epg.com/files/morocco1.xml','Open-EPG Morocco 1','MA',50),
  ('EPG','https://www.open-epg.com/files/morocco2.xml','Open-EPG Morocco 2','MA',50),
  ('EPG','https://www.open-epg.com/files/mozambique1.xml','Open-EPG Mozambique 1','MZ',50),
  ('EPG','https://www.open-epg.com/files/namibia1.xml','Open-EPG Namibia 1','NA',50),
  ('EPG','https://www.open-epg.com/files/netherlands.xml','Open-EPG Netherlands','NL',50),
  ('EPG','https://www.open-epg.com/files/newcaledonia1.xml','Open-EPG New Caledonia 1','NC',50),
  ('EPG','https://www.open-epg.com/files/newzealand1.xml','Open-EPG New Zealand 1','NZ',50),
  ('EPG','https://www.open-epg.com/files/newzealand2.xml','Open-EPG New Zealand 2','NZ',50),
  ('EPG','https://www.open-epg.com/files/nigeria1.xml','Open-EPG Nigeria 1','NG',50),
  ('EPG','https://www.open-epg.com/files/norway1.xml','Open-EPG Norway 1','NO',50),
  ('EPG','https://www.open-epg.com/files/norway2.xml','Open-EPG Norway 2','NO',50),
  ('EPG','https://www.open-epg.com/files/pakistan2.xml','Open-EPG Pakistan 2','PK',50),
  ('EPG','https://www.open-epg.com/files/pakistan4.xml','Open-EPG Pakistan 4','PK',50),
  ('EPG','https://www.open-epg.com/files/panama1.xml','Open-EPG Panama 1','PA',50),
  ('EPG','https://www.open-epg.com/files/paraguay1.xml','Open-EPG Paraguay 1','PY',50),
  ('EPG','https://www.open-epg.com/files/paraguay2.xml','Open-EPG Paraguay 2','PY',50),
  ('EPG','https://www.open-epg.com/files/peru1.xml','Open-EPG Peru 1','PE',50),
  ('EPG','https://www.open-epg.com/files/peru2.xml','Open-EPG Peru 2','PE',50),
  ('EPG','https://www.open-epg.com/files/peru3.xml','Open-EPG Peru 3','PE',50),
  ('EPG','https://www.open-epg.com/files/philippines1.xml','Open-EPG Philippines 1','PH',50),
  ('EPG','https://www.open-epg.com/files/philippines2.xml','Open-EPG Philippines 2','PH',50),
  ('EPG','https://www.open-epg.com/files/poland1.xml','Open-EPG Poland 1','PL',50),
  ('EPG','https://www.open-epg.com/files/poland2.xml','Open-EPG Poland 2','PL',50),
  ('EPG','https://www.open-epg.com/files/portugal1.xml','Open-EPG Portugal 1','PT',50),
  ('EPG','https://www.open-epg.com/files/portugal2.xml','Open-EPG Portugal 2','PT',50),
  ('EPG','https://www.open-epg.com/files/puertorico1.xml','Open-EPG Puerto Rico 1','PR',50),
  ('EPG','https://www.open-epg.com/files/puertorico2.xml','Open-EPG Puerto Rico 2','PR',50),
  ('EPG','https://www.open-epg.com/files/qatar1.xml','Open-EPG Qatar 1','QA',50),
  ('EPG','https://www.open-epg.com/files/qatar2.xml','Open-EPG Qatar 2','QA',50),
  ('EPG','https://www.open-epg.com/files/qatar3.xml','Open-EPG Qatar 3','QA',50),
  ('EPG','https://www.open-epg.com/files/qatar4.xml','Open-EPG Qatar 4','QA',50),
  ('EPG','https://www.open-epg.com/files/qatar5.xml','Open-EPG Qatar 5','QA',50),
  ('EPG','https://www.open-epg.com/files/qatar6.xml','Open-EPG Qatar 6','QA',50),
  ('EPG','https://www.open-epg.com/files/reunion1.xml','Open-EPG Réunion 1','RE',50),
  ('EPG','https://www.open-epg.com/files/romania2.xml','Open-EPG Romania 2','RO',50),
  ('EPG','https://www.open-epg.com/files/russia1.xml','Open-EPG Russia 1','RU',50),
  ('EPG','https://www.open-epg.com/files/russia2.xml','Open-EPG Russia 2','RU',50),
  ('EPG','https://www.open-epg.com/files/russia3.xml','Open-EPG Russia 3','RU',50),
  ('EPG','https://www.open-epg.com/files/saudiarabia1.xml','Open-EPG Saudi Arabia 1','SA',50),
  ('EPG','https://www.open-epg.com/files/saudiarabia2.xml','Open-EPG Saudi Arabia 2','SA',50),
  ('EPG','https://www.open-epg.com/files/saudiarabia3.xml','Open-EPG Saudi Arabia 3','SA',50),
  ('EPG','https://www.open-epg.com/files/saudiarabia4.xml','Open-EPG Saudi Arabia 4','SA',50),
  ('EPG','https://www.open-epg.com/files/saudiarabia5.xml','Open-EPG Saudi Arabia 5','SA',50),
  ('EPG','https://www.open-epg.com/files/scotland1.xml','Open-EPG Scotland 1','GB',50),
  ('EPG','https://www.open-epg.com/files/senegal1.xml','Open-EPG Senegal 1','SN',50),
  ('EPG','https://www.open-epg.com/files/serbia1.xml','Open-EPG Serbia 1','RS',50),
  ('EPG','https://www.open-epg.com/files/serbia2.xml','Open-EPG Serbia 2','RS',50),
  ('EPG','https://www.open-epg.com/files/serbia4.xml','Open-EPG Serbia 4','RS',50),
  ('EPG','https://www.open-epg.com/files/serbia5.xml','Open-EPG Serbia 5','RS',50),
  ('EPG','https://www.open-epg.com/files/singapore1.xml','Open-EPG Singapore 1','SG',50),
  ('EPG','https://www.open-epg.com/files/singapore2.xml','Open-EPG Singapore 2','SG',50),
  ('EPG','https://www.open-epg.com/files/singapore3.xml','Open-EPG Singapore 3','SG',50),
  ('EPG','https://www.open-epg.com/files/slovakia1.xml','Open-EPG Slovakia 1','SK',50),
  ('EPG','https://www.open-epg.com/files/slovakia2.xml','Open-EPG Slovakia 2','SK',50),
  ('EPG','https://www.open-epg.com/files/slovakia3.xml','Open-EPG Slovakia 3','SK',50),
  ('EPG','https://www.open-epg.com/files/slovenia1.xml','Open-EPG Slovenia 1','SI',50),
  ('EPG','https://www.open-epg.com/files/slovenia2.xml','Open-EPG Slovenia 2','SI',50),
  ('EPG','https://www.open-epg.com/files/southafrica1.xml','Open-EPG South Africa 1','ZA',50),
  ('EPG','https://www.open-epg.com/files/southafrica2.xml','Open-EPG South Africa 2','ZA',50),
  ('EPG','https://www.open-epg.com/files/spain1.xml','Open-EPG Spain 1','ES',50),
  ('EPG','https://www.open-epg.com/files/spain2.xml','Open-EPG Spain 2','ES',50),
  ('EPG','https://www.open-epg.com/files/spain3.xml','Open-EPG Spain 3','ES',50),
  ('EPG','https://www.open-epg.com/files/spain4.xml','Open-EPG Spain 4','ES',50),
  ('EPG','https://www.open-epg.com/files/spain5.xml','Open-EPG Spain 5','ES',50),
  ('EPG','https://www.open-epg.com/files/spain6.xml','Open-EPG Spain 6','ES',50),
  ('EPG','https://www.open-epg.com/files/sports1.xml','Open-EPG Sports 1',NULL,50),
  ('EPG','https://www.open-epg.com/files/sports2.xml','Open-EPG Sports 2',NULL,50),
  ('EPG','https://www.open-epg.com/files/sports4.xml','Open-EPG Sports 4',NULL,50),
  ('EPG','https://www.open-epg.com/files/sports5.xml','Open-EPG Sports 5',NULL,50),
  ('EPG','https://www.open-epg.com/files/sweden1.xml','Open-EPG Sweden 1','SE',50),
  ('EPG','https://www.open-epg.com/files/sweden2.xml','Open-EPG Sweden 2','SE',50),
  ('EPG','https://www.open-epg.com/files/sweden3.xml','Open-EPG Sweden 3','SE',50),
  ('EPG','https://www.open-epg.com/files/sweden4.xml','Open-EPG Sweden 4','SE',50),
  ('EPG','https://www.open-epg.com/files/switzerland2.xml','Open-EPG Switzerland 2','CH',50),
  ('EPG','https://www.open-epg.com/files/switzerland3.xml','Open-EPG Switzerland 3','CH',50),
  ('EPG','https://www.open-epg.com/files/switzerland4.xml','Open-EPG Switzerland 4','CH',50),
  ('EPG','https://www.open-epg.com/files/taiwan1.xml','Open-EPG Taiwan 1','TW',50),
  ('EPG','https://www.open-epg.com/files/taiwan2.xml','Open-EPG Taiwan 2','TW',50),
  ('EPG','https://www.open-epg.com/files/thailand1.xml','Open-EPG Thailand 1','TH',50),
  ('EPG','https://www.open-epg.com/files/thailand2.xml','Open-EPG Thailand 2','TH',50),
  ('EPG','https://www.open-epg.com/files/trinidad1.xml','Open-EPG Trinidad 1','TT',50),
  ('EPG','https://www.open-epg.com/files/turkey1.xml','Open-EPG Turkey 1','TR',50),
  ('EPG','https://www.open-epg.com/files/turkey2.xml','Open-EPG Turkey 2','TR',50),
  ('EPG','https://www.open-epg.com/files/turkey3.xml','Open-EPG Turkey 3','TR',50),
  ('EPG','https://www.open-epg.com/files/turkey4.xml','Open-EPG Turkey 4','TR',50),
  ('EPG','https://www.open-epg.com/files/turkey5.xml','Open-EPG Turkey 5','TR',50),
  ('EPG','https://www.open-epg.com/files/uae6.xml','Open-EPG United Arab Emirates 6','AE',50),
  ('EPG','https://www.open-epg.com/files/uganda1.xml','Open-EPG Uganda 1','UG',50),
  ('EPG','https://www.open-epg.com/files/ukraine1.xml','Open-EPG Ukraine 1','UA',50),
  ('EPG','https://www.open-epg.com/files/unitedkingdom1.xml','Open-EPG United Kingdom 1','GB',50),
  ('EPG','https://www.open-epg.com/files/unitedkingdom2.xml','Open-EPG United Kingdom 2','GB',50),
  ('EPG','https://www.open-epg.com/files/unitedkingdom3.xml','Open-EPG United Kingdom 3','GB',50),
  ('EPG','https://www.open-epg.com/files/unitedkingdom4.xml','Open-EPG United Kingdom 4','GB',50),
  ('EPG','https://www.open-epg.com/files/unitedkingdom5.xml','Open-EPG United Kingdom 5','GB',50),
  ('EPG','https://www.open-epg.com/files/unitedstates1.xml','Open-EPG United States 1','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates2.xml','Open-EPG United States 2','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates3.xml','Open-EPG United States 3','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates4.xml','Open-EPG United States 4','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates5.xml','Open-EPG United States 5','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates6.xml','Open-EPG United States 6','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates7.xml','Open-EPG United States 7','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates8.xml','Open-EPG United States 8','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates9.xml','Open-EPG United States 9','US',50),
  ('EPG','https://www.open-epg.com/files/unitedstates10.xml','Open-EPG United States 10','US',50),
  ('EPG','https://www.open-epg.com/files/uruguay1.xml','Open-EPG Uruguay 1','UY',50),
  ('EPG','https://www.open-epg.com/files/uruguay2.xml','Open-EPG Uruguay 2','UY',50),
  ('EPG','https://www.open-epg.com/files/uzbekistan1.xml','Open-EPG Uzbekistan 1','UZ',50),
  ('EPG','https://www.open-epg.com/files/venezuela1.xml','Open-EPG Venezuela 1','VE',50),
  ('EPG','https://www.open-epg.com/files/vietnam1.xml','Open-EPG Vietnam 1','VN',50),
  ('EPG','https://www.open-epg.com/files/zambia1.xml','Open-EPG Zambia 1','ZM',50)
ON CONFLICT DO NOTHING;


INSERT INTO data_source(type, url, label, priority) VALUES
  ('M3U','https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8','Free-TV master playlist',50)
ON CONFLICT DO NOTHING;